### ISSUE TITLE
Duda Programa Sine_Wave_Gen

### ISSUE THREAD

**Issue by adolfoaranaes12** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#1]
Buenas tardes, espero se encuentren bien. Una duda ¿una vez que terminemos con las actividades éstas se suben a algún lugar?
Muchas gracias de antemano por su apoyo. Reciban un cordial saludo.

Adolfo Arana Espíritu Santo

**Comment by mariomartinezgro** [comment]
Hola Adolfo, 
No, esas son actividades para que ustedes la realicen durante la clase  solamente y puedan aprender ROS.

Saludos
