### ISSUE TITLE
Grabaciones sesiones

### ISSUE THREAD

**Issue by rickycvs** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#2]
Buen día,

¿Dónde podría revisar las grabaciones de las sesiones 2 y 3? En la sección Live Session Recordings solo aparece la de la sesión 1.

Gracias.

**Comment by mariomartinezgro** [comment]
Las grabaciones de las sesiones ya esta disponibles en github 

Saludos
