### ISSUE TITLE
Problemas Instalando catkin

### ISSUE THREAD

**Issue by Unides271** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#3]
Al momento de ejecutar "catkin_make" aparece error: No se ha encontrado la orden <<catkin_make>>, pero se puede instalar con: sudo apt installe catkin

Y cuando ejecuto "sudo apt installe catkin" da un error diciendo: 
Los siguientes paquetes tienen dependencias incumplidas:
catkin : Depende: python3-catkin-pkg pero no va a instalarse. 
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos. 

Finalmente cuando quiero instalar: sudo apt-get install python-catkin-pkg da un error mencionando no tiene un candidato para la instalación.

**Comment by mariomartinezgro** [comment]
Verifica que no estes haciendo catkin_make desde otra carpeta, catkin_make debe utilizarse solo dentro de la carpeta catkin_ws

Si aun tienes este problema, mandame un screenshot y lo podemos ver mas a detalle

Saludos
