### ISSUE TITLE
Partición de Challenge

### ISSUE THREAD

**Issue by Fam70** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#4]
Buen día, profesores!

Por parte del grupo 1 de SC queríamos saber la forma en cómo se va a realizar el Challenge mencionado en la clase anterior. Si de forma individual o por equipos.

Esto debido a la gran cantidad de actividades a realizar que involucran un nivel más avanzado que el de "aprendizaje", que es en el que nos encontramos ahorita, en especial con ROS. Ya que hay de varias carreras, en su mayoría IFI, IMT, IM e IE, que no se especializan en dicha área.

No obstante, estaremos pendientes de la decisión que ustedes tomen.
Gracias por su tiempo!

**Comment by mariomartinezgro** [comment]
Hola, 
El reto esta disenado para ser solucionado usando los conocimientos recibidos durante la clase, ya que no requieren un nivel avanzado de programacion ni de ROS. El reto, tal y como dice las reglas sera de manera individual, utilizando los conocimientos adquiridos durante el curso. El dia Lunes, se tendra una ultima sesion de asesorias, asi que se les sugiere a todos los alumnos que si aun hay algun tema en especifico del cual quieran hablar vengan preparados con preguntas especificas y concretas.

Saludos
