### ISSUE TITLE
Problemas ROS

### ISSUE THREAD

**Issue by adolfoaranaes12** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#5]
Buenas tardes Profesores, espero se encuentren bien. Disculpen, no sé a qué le moví al Ubuntu (al que ustedes nos proporcionaron), pero el día de hoy me comenzó a aparecer este error:
![Capture](https://user-images.githubusercontent.com/18265555/189000162-47e7b9c3-b0ac-4b55-9280-977139eafa0d.PNG)
Ya revisé tener mis archivos ejecutables, y sí los tengo, cree incluso un nuevo workspace y copie los paquetes que nos proporcionaron en el github y sigo sin ser capaz de resolver este error. Incluso ya no me aparece el robot en el mapa:
![image](https://user-images.githubusercontent.com/18265555/189000390-1e549e0c-5998-422b-8fa1-3099a5a60114.png)

Muchas gracias de antemano por su apoyo. Reciban un cordial saludo.

Adolfo Arana Espíritu Santo

**Comment by rebecavelasco** [comment]
Hola Adolfo.  Es un poco extraño el error, si ya se había corrido antes.  Te recomiendo lo siguiente:

1. Puede ser porque el server que corre gazebo se haya quedó colgado. Usa los siguientes comandos para forzar el cierre y vuelve a intentarlo. 

killall gzserver
killall gzclient

2. Verifica que las dependencias de  ROS control estén instaladas.

El comando para instalar esto está en la diapositiva de la primera clase, en un recuadro azul.

Coméntame cómo vas. 

Rebeca

**Comment by adolfoaranaes12** [comment]
Ya quedó resuelto, muchas gracias por su apoyo.
