### ISSUE TITLE
Asesoria

### ISSUE THREAD

**Issue by A00227526** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#6]
Buenas tardes, disculpen, quería saber si me podrían dar un poco de tiempo para tener una asesoría debido a que tengo problemas con ros nativo, este no me esta instalando ningún paquete marcándome que no los encuentra y no he podido resolverlo, he estado usando la maquina virtual pero quería resolver lo de mi ros nativo

**Comment by mariomartinezgro** [comment]
El lunes durante la clase, se les dara tiempo para resolver este tipo de dudas. Por lo pronto te sugiero uses nuestra maquina virtual que te proporcionamos en la sesion 1, las instrucciones las puedes encontrar el en github

Saludos
