### ISSUE TITLE
Petición para extender la fecha de entrega Challenge

### ISSUE THREAD

**Issue by DanyMont** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#7]
Hola buenas noches, espero se encuentren bien.
Hablando con mis compañeros, pudimos notar que todos tenemos un poco de preocupación respecto a la fecha de entrega del challenge y queríamos ver si es posible recorrerla. Después de un consenso, queremos proponer una extensión para el día miércoles más entendemos que este pueda ser un lapso grande, por lo que también estamos abiertos a llegar a un acuerdo que beneficie a todos.
Agradecemos su comprensión

**Comment by mariomartinezgro** [comment]
Hola, 
Estamos trabajando junto con el profesor Carlos para ver si se puede hacer algo al respecto, ya que nosotros somos un socio formador y no somos parte del sistema TEC. Te sugiero estar al pendiente de tu correo en las proximas horas donde se les informara de la decision que se tome. Por el momento, si tienes dudas o preguntas puedes contactarnos por aqui o mandar un correo al profesor Carlos que nos la hara llegar a la brevedad.

Saludos
