### ISSUE TITLE
Problemas con rosrun

### ISSUE THREAD

**Issue by gabyvillaruiz** [ManchesterRoboticsLtd/Sistemas-ciberfisicos-TEC-Intro-ROS#8]
Buenas noches.

Lo que pasa es que cuando intento correr un nodo, en ocasiones me aparece este error, supuse que era porque me hacía falta hacer ejecutable el código con chmod +x, pero sigue apareciendome. No es la primera vez que me pasa, ya me había salido en ocasiones anteriores, pero esto ya no me permite probar lo de la actividad. Anexo fotos de lo que me aparece.

![image](https://user-images.githubusercontent.com/78065494/190544458-18ead9cd-232e-40ef-82df-40993dd4dae2.png)

Saludos y bonita noche.

**Comment by mariomartinezgro** [comment]
Hola Gaby, 
Ese mensaje marca que quizas hay un error en tu codigo. Cuando descargas el ejemplo que se te dio en github (straighline.py) sin modificarlo lo puedes correr? O tienes probelmas? Estas usando la virtual machine? O dual booting?

Tambien si pudieras adjuntar tu codigo al mensaje ppdria ver donde esta tu problema.

Saludos,
Mario

**Comment by gabyvillaruiz** [comment]
Gracias! Ya quedó solucionado
